#include "encoder.h"

#include "isa.h"

#include <ctype.h>
#include <string.h>

#define INSTRUCTION(name, opcode, format) {name, opcode, format}

static const AsmInstructionSpec INSTRUCTIONS[] = {
    INSTRUCTION("HALT", OP_HALT, ASM_FORMAT_NONE),
    INSTRUCTION("MOVI64", OP_MOVI64, ASM_FORMAT_R_IMM64),
    INSTRUCTION("ADD", OP_ADD, ASM_FORMAT_RR),
    INSTRUCTION("LOAD8U", OP_LOAD8U, ASM_FORMAT_RR),
    INSTRUCTION("STORE8", OP_STORE8, ASM_FORMAT_RR),
    INSTRUCTION("JUMP", OP_JUMP, ASM_FORMAT_TARGET64),
    INSTRUCTION("CALL", OP_CALL, ASM_FORMAT_TARGET64),
    INSTRUCTION("RET", OP_RET, ASM_FORMAT_NONE),
    INSTRUCTION("MOV", OP_MOV, ASM_FORMAT_RR),
    INSTRUCTION("LOAD16U", OP_LOAD16U, ASM_FORMAT_RR),
    INSTRUCTION("LOAD32U", OP_LOAD32U, ASM_FORMAT_RR),
    INSTRUCTION("LOAD64", OP_LOAD64, ASM_FORMAT_RR),
    INSTRUCTION("LOAD8S", OP_LOAD8S, ASM_FORMAT_RR),
    INSTRUCTION("LOAD16S", OP_LOAD16S, ASM_FORMAT_RR),
    INSTRUCTION("LOAD32S", OP_LOAD32S, ASM_FORMAT_RR),
    INSTRUCTION("STORE16", OP_STORE16, ASM_FORMAT_RR),
    INSTRUCTION("STORE32", OP_STORE32, ASM_FORMAT_RR),
    INSTRUCTION("STORE64", OP_STORE64, ASM_FORMAT_RR),
    INSTRUCTION("SUB", OP_SUB, ASM_FORMAT_RR),
    INSTRUCTION("MUL", OP_MUL, ASM_FORMAT_RR),
    INSTRUCTION("DIVU", OP_DIVU, ASM_FORMAT_RR),
    INSTRUCTION("DIVS", OP_DIVS, ASM_FORMAT_RR),
    INSTRUCTION("MODU", OP_MODU, ASM_FORMAT_RR),
    INSTRUCTION("MODS", OP_MODS, ASM_FORMAT_RR),
    INSTRUCTION("AND", OP_AND, ASM_FORMAT_RR),
    INSTRUCTION("OR", OP_OR, ASM_FORMAT_RR),
    INSTRUCTION("XOR", OP_XOR, ASM_FORMAT_RR),
    INSTRUCTION("NOT", OP_NOT, ASM_FORMAT_R),
    INSTRUCTION("SHL", OP_SHL, ASM_FORMAT_R_U8),
    INSTRUCTION("SHR", OP_SHR, ASM_FORMAT_R_U8),
    INSTRUCTION("SAR", OP_SAR, ASM_FORMAT_R_U8),
    INSTRUCTION("CMP", OP_CMP, ASM_FORMAT_RR),
    INSTRUCTION("JZ", OP_JZ, ASM_FORMAT_TARGET64),
    INSTRUCTION("JNZ", OP_JNZ, ASM_FORMAT_TARGET64),
    INSTRUCTION("JLT", OP_JLT, ASM_FORMAT_TARGET64),
    INSTRUCTION("JLE", OP_JLE, ASM_FORMAT_TARGET64),
    INSTRUCTION("JGT", OP_JGT, ASM_FORMAT_TARGET64),
    INSTRUCTION("JGE", OP_JGE, ASM_FORMAT_TARGET64),
    INSTRUCTION("JLTU", OP_JLTU, ASM_FORMAT_TARGET64),
    INSTRUCTION("JLEU", OP_JLEU, ASM_FORMAT_TARGET64),
    INSTRUCTION("JGTU", OP_JGTU, ASM_FORMAT_TARGET64),
    INSTRUCTION("JGEU", OP_JGEU, ASM_FORMAT_TARGET64),
    INSTRUCTION("PUSH", OP_PUSH, ASM_FORMAT_R),
    INSTRUCTION("POP", OP_POP, ASM_FORMAT_R),
    INSTRUCTION("NOP", OP_NOP, ASM_FORMAT_NONE),
    INSTRUCTION("IRET", OP_IRET, ASM_FORMAT_NONE),
    INSTRUCTION("EI", OP_EI, ASM_FORMAT_NONE),
    INSTRUCTION("DI", OP_DI, ASM_FORMAT_NONE),
    INSTRUCTION("CAS64", OP_CAS64, ASM_FORMAT_RRRR),
    INSTRUCTION("XCHG64", OP_XCHG64, ASM_FORMAT_RR),
    INSTRUCTION("ATOMIC_ADD64", OP_ATOMIC_ADD64, ASM_FORMAT_RRR),
    INSTRUCTION("FENCE", OP_FENCE, ASM_FORMAT_NONE),
    INSTRUCTION("COREID", OP_COREID, ASM_FORMAT_R),
    INSTRUCTION("THREADID", OP_THREADID, ASM_FORMAT_R),
    INSTRUCTION("WAIT", OP_WAIT, ASM_FORMAT_NONE),
    INSTRUCTION("EXCAUSE", OP_EXCAUSE, ASM_FORMAT_R),
    INSTRUCTION("EXADDR", OP_EXADDR, ASM_FORMAT_R),
    INSTRUCTION("SETVBR", OP_SETVBR, ASM_FORMAT_R),
    INSTRUCTION("GETVBR", OP_GETVBR, ASM_FORMAT_R),
    INSTRUCTION("GETMODE", OP_GETMODE, ASM_FORMAT_R),
    INSTRUCTION("ENTERUSER", OP_ENTERUSER, ASM_FORMAT_NONE),
    INSTRUCTION("SETPTBR", OP_SETPTBR, ASM_FORMAT_R),
    INSTRUCTION("GETPTBR", OP_GETPTBR, ASM_FORMAT_R),
    INSTRUCTION("MMUON", OP_MMUON, ASM_FORMAT_NONE),
    INSTRUCTION("MMUOFF", OP_MMUOFF, ASM_FORMAT_NONE),
    INSTRUCTION("GETMMU", OP_GETMMU, ASM_FORMAT_R),
    INSTRUCTION("EXPC", OP_EXPC, ASM_FORMAT_R),
    INSTRUCTION("EXINFO", OP_EXINFO, ASM_FORMAT_R),
    INSTRUCTION("JUMPR", OP_JUMPR, ASM_FORMAT_R),
    INSTRUCTION("CALLR", OP_CALLR, ASM_FORMAT_R),
    INSTRUCTION("SHLV", OP_SHLV, ASM_FORMAT_RR),
    INSTRUCTION("SHRV", OP_SHRV, ASM_FORMAT_RR),
    INSTRUCTION("SARV", OP_SARV, ASM_FORMAT_RR),
    INSTRUCTION("MOVI32U", OP_MOVI32U, ASM_FORMAT_R_IMM32U),
    INSTRUCTION("MOVI32S", OP_MOVI32S, ASM_FORMAT_R_IMM32S),
    INSTRUCTION("ADDI32", OP_ADDI32, ASM_FORMAT_R_IMM32S),
    INSTRUCTION("CMPI32", OP_CMPI32, ASM_FORMAT_R_IMM32S),
    INSTRUCTION("ANDI32", OP_ANDI32, ASM_FORMAT_R_IMM32U),
    INSTRUCTION("ORI32", OP_ORI32, ASM_FORMAT_R_IMM32U),
    INSTRUCTION("XORI32", OP_XORI32, ASM_FORMAT_R_IMM32U),
    INSTRUCTION("TESTI32", OP_TESTI32, ASM_FORMAT_R_IMM32U),
    INSTRUCTION("LEA", OP_LEA, ASM_FORMAT_RR_DISP32),
    INSTRUCTION("LOAD8UO", OP_LOAD8UO, ASM_FORMAT_RR_DISP32),
    INSTRUCTION("LOAD16UO", OP_LOAD16UO, ASM_FORMAT_RR_DISP32),
    INSTRUCTION("LOAD32UO", OP_LOAD32UO, ASM_FORMAT_RR_DISP32),
    INSTRUCTION("LOAD64O", OP_LOAD64O, ASM_FORMAT_RR_DISP32),
    INSTRUCTION("LOAD8SO", OP_LOAD8SO, ASM_FORMAT_RR_DISP32),
    INSTRUCTION("LOAD16SO", OP_LOAD16SO, ASM_FORMAT_RR_DISP32),
    INSTRUCTION("LOAD32SO", OP_LOAD32SO, ASM_FORMAT_RR_DISP32),
    INSTRUCTION("STORE8O", OP_STORE8O, ASM_FORMAT_RR_DISP32),
    INSTRUCTION("STORE16O", OP_STORE16O, ASM_FORMAT_RR_DISP32),
    INSTRUCTION("STORE32O", OP_STORE32O, ASM_FORMAT_RR_DISP32),
    INSTRUCTION("STORE64O", OP_STORE64O, ASM_FORMAT_RR_DISP32),
    INSTRUCTION("JUMPREL", OP_JUMPREL, ASM_FORMAT_REL32),
    INSTRUCTION("BRCC", OP_BRCC, ASM_FORMAT_CC_REL32),
    INSTRUCTION("CALLREL", OP_CALLREL, ASM_FORMAT_REL32),
    INSTRUCTION("SEXT8", OP_SEXT8, ASM_FORMAT_RR),
    INSTRUCTION("SEXT16", OP_SEXT16, ASM_FORMAT_RR),
    INSTRUCTION("SEXT32", OP_SEXT32, ASM_FORMAT_RR),
    INSTRUCTION("ZEXT8", OP_ZEXT8, ASM_FORMAT_RR),
    INSTRUCTION("ZEXT16", OP_ZEXT16, ASM_FORMAT_RR),
    INSTRUCTION("ZEXT32", OP_ZEXT32, ASM_FORMAT_RR),
    INSTRUCTION("SYSCALL", OP_SYSCALL, ASM_FORMAT_NONE),
    INSTRUCTION("SETKSP", OP_SETKSP, ASM_FORMAT_R),
    INSTRUCTION("GETKSP", OP_GETKSP, ASM_FORMAT_R),
    INSTRUCTION("VLOAD128", OP_VLOAD128, ASM_FORMAT_V_R),
    INSTRUCTION("VSTORE128", OP_VSTORE128, ASM_FORMAT_R_V),
    INSTRUCTION("VMOV", OP_VMOV, ASM_FORMAT_VV),
    INSTRUCTION("VADD8", OP_VADD8, ASM_FORMAT_VVV),
    INSTRUCTION("VADD16", OP_VADD16, ASM_FORMAT_VVV),
    INSTRUCTION("VADD32", OP_VADD32, ASM_FORMAT_VVV),
    INSTRUCTION("VADD64", OP_VADD64, ASM_FORMAT_VVV),
    INSTRUCTION("VSUB8", OP_VSUB8, ASM_FORMAT_VVV),
    INSTRUCTION("VSUB16", OP_VSUB16, ASM_FORMAT_VVV),
    INSTRUCTION("VSUB32", OP_VSUB32, ASM_FORMAT_VVV),
    INSTRUCTION("VSUB64", OP_VSUB64, ASM_FORMAT_VVV),
    INSTRUCTION("VMUL8", OP_VMUL8, ASM_FORMAT_VVV),
    INSTRUCTION("VMUL16", OP_VMUL16, ASM_FORMAT_VVV),
    INSTRUCTION("VMUL32", OP_VMUL32, ASM_FORMAT_VVV),
    INSTRUCTION("VMUL64", OP_VMUL64, ASM_FORMAT_VVV),
    INSTRUCTION("VAND", OP_VAND, ASM_FORMAT_VVV),
    INSTRUCTION("VOR", OP_VOR, ASM_FORMAT_VVV),
    INSTRUCTION("VXOR", OP_VXOR, ASM_FORMAT_VVV),
    INSTRUCTION("FLOAD32", OP_FLOAD32, ASM_FORMAT_V_R),
    INSTRUCTION("FLOAD64", OP_FLOAD64, ASM_FORMAT_V_R),
    INSTRUCTION("FSTORE32", OP_FSTORE32, ASM_FORMAT_R_V),
    INSTRUCTION("FSTORE64", OP_FSTORE64, ASM_FORMAT_R_V),
    INSTRUCTION("FADD32", OP_FADD32, ASM_FORMAT_VVV),
    INSTRUCTION("FADD64", OP_FADD64, ASM_FORMAT_VVV),
    INSTRUCTION("FSUB32", OP_FSUB32, ASM_FORMAT_VVV),
    INSTRUCTION("FSUB64", OP_FSUB64, ASM_FORMAT_VVV),
    INSTRUCTION("FMUL32", OP_FMUL32, ASM_FORMAT_VVV),
    INSTRUCTION("FMUL64", OP_FMUL64, ASM_FORMAT_VVV),
    INSTRUCTION("FDIV32", OP_FDIV32, ASM_FORMAT_VVV),
    INSTRUCTION("FDIV64", OP_FDIV64, ASM_FORMAT_VVV),
    INSTRUCTION("FCMP32", OP_FCMP32, ASM_FORMAT_VV),
    INSTRUCTION("FCMP64", OP_FCMP64, ASM_FORMAT_VV),
    INSTRUCTION("FNEG32", OP_FNEG32, ASM_FORMAT_VV),
    INSTRUCTION("FNEG64", OP_FNEG64, ASM_FORMAT_VV),
    INSTRUCTION("FABS32", OP_FABS32, ASM_FORMAT_VV),
    INSTRUCTION("FABS64", OP_FABS64, ASM_FORMAT_VV),
    INSTRUCTION("I32TOF32", OP_I32TOF32, ASM_FORMAT_V_R),
    INSTRUCTION("I64TOF64", OP_I64TOF64, ASM_FORMAT_V_R),
    INSTRUCTION("F32TOI32", OP_F32TOI32, ASM_FORMAT_R_V),
    INSTRUCTION("F64TOI64", OP_F64TOI64, ASM_FORMAT_R_V),
    INSTRUCTION("VFADD32", OP_VFADD32, ASM_FORMAT_VVV),
    INSTRUCTION("VFADD64", OP_VFADD64, ASM_FORMAT_VVV),
    INSTRUCTION("VFSUB32", OP_VFSUB32, ASM_FORMAT_VVV),
    INSTRUCTION("VFSUB64", OP_VFSUB64, ASM_FORMAT_VVV),
    INSTRUCTION("VFMUL32", OP_VFMUL32, ASM_FORMAT_VVV),
    INSTRUCTION("VFMUL64", OP_VFMUL64, ASM_FORMAT_VVV),
    INSTRUCTION("VFDIV32", OP_VFDIV32, ASM_FORMAT_VVV),
    INSTRUCTION("VFDIV64", OP_VFDIV64, ASM_FORMAT_VVV),
    INSTRUCTION("F32TOF64", OP_F32TOF64, ASM_FORMAT_VV),
    INSTRUCTION("F64TOF32", OP_F64TOF32, ASM_FORMAT_VV),
    INSTRUCTION("GETFPSTATUS", OP_GETFPSTATUS, ASM_FORMAT_R),
    INSTRUCTION("CLEARFPSTATUS", OP_CLEARFPSTATUS, ASM_FORMAT_NONE)
};

int asm_text_equal_ignore_case(const char *left, const char *right)
{
    if (left == NULL || right == NULL) {
        return 0;
    }
    while (*left != '\0' && *right != '\0') {
        if (toupper((unsigned char)*left) !=
            toupper((unsigned char)*right)) {
            return 0;
        }
        ++left;
        ++right;
    }
    return *left == '\0' && *right == '\0';
}

const AsmInstructionSpec *asm_instruction_find(const char *name)
{
    for (size_t i = 0;
         i < sizeof(INSTRUCTIONS) / sizeof(INSTRUCTIONS[0]);
         ++i) {
        if (asm_text_equal_ignore_case(INSTRUCTIONS[i].name, name)) {
            return &INSTRUCTIONS[i];
        }
    }
    return NULL;
}

size_t asm_instruction_size(AsmInstructionFormat format)
{
    switch (format) {
        case ASM_FORMAT_NONE: return 1;
        case ASM_FORMAT_R: return 2;
        case ASM_FORMAT_RR: return 3;
        case ASM_FORMAT_RRR: return 4;
        case ASM_FORMAT_RRRR: return 5;
        case ASM_FORMAT_R_IMM64: return 10;
        case ASM_FORMAT_R_IMM32U:
        case ASM_FORMAT_R_IMM32S: return 6;
        case ASM_FORMAT_R_U8: return 3;
        case ASM_FORMAT_TARGET64: return 9;
        case ASM_FORMAT_RR_DISP32: return 7;
        case ASM_FORMAT_REL32: return 5;
        case ASM_FORMAT_CC_REL32: return 6;
        case ASM_FORMAT_V_R:
        case ASM_FORMAT_R_V:
        case ASM_FORMAT_VV: return 3;
        case ASM_FORMAT_VVV: return 4;
    }
    return 0;
}

int asm_parse_register(const char *text, uint8_t *reg)
{
    if (text == NULL || reg == NULL) {
        return 0;
    }
    if (asm_text_equal_ignore_case(text, "SP")) {
        *reg = REGISTER_SP;
        return 1;
    }
    if (toupper((unsigned char)text[0]) != 'R' || text[1] == '\0') {
        return 0;
    }
    unsigned int value = 0;
    for (size_t i = 1; text[i] != '\0'; ++i) {
        if (text[i] < '0' || text[i] > '9') {
            return 0;
        }
        value = value * 10 + (unsigned int)(text[i] - '0');
        if (value >= REGISTER_COUNT) {
            return 0;
        }
    }
    *reg = (uint8_t)value;
    return 1;
}

int asm_parse_vector_register(const char *text, uint8_t *reg)
{
    if (text == NULL || reg == NULL ||
        toupper((unsigned char)text[0]) != 'V' || text[1] == '\0') {
        return 0;
    }
    unsigned int value = 0;
    for (size_t i = 1; text[i] != '\0'; ++i) {
        if (text[i] < '0' || text[i] > '9') {
            return 0;
        }
        value = value * 10 + (unsigned int)(text[i] - '0');
        if (value >= VECTOR_REGISTER_COUNT) {
            return 0;
        }
    }
    *reg = (uint8_t)value;
    return 1;
}

int asm_parse_condition(const char *text, uint8_t *condition)
{
    static const char *const NAMES[CPU_CONDITION_COUNT] = {
        "ALWAYS", "EQ", "NE", "LT", "LE", "GT",
        "GE", "LTU", "LEU", "GTU", "GEU", "ORD", "UNO"
    };
    if (text == NULL || condition == NULL) {
        return 0;
    }
    for (uint8_t i = 0; i < CPU_CONDITION_COUNT; ++i) {
        if (asm_text_equal_ignore_case(text, NAMES[i])) {
            *condition = i;
            return 1;
        }
    }
    return 0;
}
