#ifndef VM_BLOCK_PROTOCOL_H
#define VM_BLOCK_PROTOCOL_H

#include <stdint.h>

#define VM_BLOCK_MAGIC UINT64_C(0x314B4C42564D)
#define VM_BLOCK_VERSION UINT64_C(1)
#define VM_BLOCK_SECTOR_SIZE UINT64_C(512)
#define VM_BLOCK_MAX_TRANSFER_SECTORS UINT64_C(128)
#define VM_BLOCK_MMIO_SIZE UINT64_C(4096)

#define VM_BLOCK_MAGIC_OFFSET        UINT64_C(0x00)
#define VM_BLOCK_VERSION_OFFSET      UINT64_C(0x08)
#define VM_BLOCK_FEATURES_OFFSET     UINT64_C(0x10)
#define VM_BLOCK_CAPACITY_OFFSET     UINT64_C(0x18)
#define VM_BLOCK_SECTOR_SIZE_OFFSET  UINT64_C(0x20)
#define VM_BLOCK_MAX_TRANSFER_OFFSET UINT64_C(0x28)
#define VM_BLOCK_LBA_OFFSET          UINT64_C(0x30)
#define VM_BLOCK_DMA_ADDRESS_OFFSET  UINT64_C(0x38)
#define VM_BLOCK_SECTOR_COUNT_OFFSET UINT64_C(0x40)
#define VM_BLOCK_COMMAND_OFFSET      UINT64_C(0x48)
#define VM_BLOCK_STATUS_OFFSET       UINT64_C(0x50)
#define VM_BLOCK_ERROR_OFFSET        UINT64_C(0x58)
#define VM_BLOCK_CONTROL_OFFSET      UINT64_C(0x60)
#define VM_BLOCK_IRQ_STATUS_OFFSET   UINT64_C(0x68)
#define VM_BLOCK_IRQ_ACK_OFFSET      UINT64_C(0x70)

#define VM_BLOCK_FEATURE_DMA       (UINT64_C(1) << 0)
#define VM_BLOCK_FEATURE_FLUSH     (UINT64_C(1) << 1)
#define VM_BLOCK_FEATURE_READ_ONLY (UINT64_C(1) << 2)

#define VM_BLOCK_COMMAND_NONE  UINT64_C(0)
#define VM_BLOCK_COMMAND_READ  UINT64_C(1)
#define VM_BLOCK_COMMAND_WRITE UINT64_C(2)
#define VM_BLOCK_COMMAND_FLUSH UINT64_C(3)

#define VM_BLOCK_STATUS_READY     (UINT64_C(1) << 0)
#define VM_BLOCK_STATUS_BUSY      (UINT64_C(1) << 1)
#define VM_BLOCK_STATUS_DONE      (UINT64_C(1) << 2)
#define VM_BLOCK_STATUS_ERROR     (UINT64_C(1) << 3)
#define VM_BLOCK_STATUS_READ_ONLY (UINT64_C(1) << 4)

#define VM_BLOCK_CONTROL_IRQ_ENABLE (UINT64_C(1) << 0)

#define VM_BLOCK_IRQ_COMPLETE (UINT64_C(1) << 0)
#define VM_BLOCK_IRQ_ERROR    (UINT64_C(1) << 1)

typedef enum {
    VM_BLOCK_ERROR_NONE = 0,
    VM_BLOCK_ERROR_BUSY = 1,
    VM_BLOCK_ERROR_COMMAND = 2,
    VM_BLOCK_ERROR_RANGE = 3,
    VM_BLOCK_ERROR_DMA = 4,
    VM_BLOCK_ERROR_IO = 5,
    VM_BLOCK_ERROR_READ_ONLY = 6,
    VM_BLOCK_ERROR_ALLOCATION = 7
} VmBlockError;

#endif
