#ifndef CVM_ABI_H
#define CVM_ABI_H

#include <stdint.h>

#define CVM_ABI_VERSION_MAJOR UINT16_C(1)
#define CVM_ABI_VERSION_MINOR UINT16_C(0)

#define CVM_ABI_BYTE_BITS UINT8_C(8)
#define CVM_ABI_POINTER_SIZE UINT8_C(8)
#define CVM_ABI_POINTER_ALIGNMENT UINT8_C(8)
#define CVM_ABI_STACK_ALIGNMENT UINT8_C(16)
#define CVM_ABI_RETURN_ADDRESS_SIZE UINT8_C(8)
#define CVM_ABI_MAX_SCALAR_ALIGNMENT UINT8_C(8)
#define CVM_ABI_VECTOR_ALIGNMENT UINT8_C(16)

#define CVM_ABI_GPR_ARGUMENT_FIRST UINT8_C(0)
#define CVM_ABI_GPR_ARGUMENT_COUNT UINT8_C(8)
#define CVM_ABI_VECTOR_ARGUMENT_FIRST UINT8_C(0)
#define CVM_ABI_VECTOR_ARGUMENT_COUNT UINT8_C(8)
#define CVM_ABI_GPR_RETURN_FIRST UINT8_C(0)
#define CVM_ABI_VECTOR_RETURN_FIRST UINT8_C(0)
#define CVM_ABI_STACK_POINTER_REGISTER UINT8_C(15)

/* ABI v1 deliberately makes every non-SP register caller-saved. */
#define CVM_ABI_GPR_CALLER_SAVED_MASK UINT16_C(0x7FFF)
#define CVM_ABI_GPR_CALLEE_SAVED_MASK UINT16_C(0x0000)
#define CVM_ABI_VECTOR_CALLER_SAVED_MASK UINT16_C(0xFFFF)
#define CVM_ABI_VECTOR_CALLEE_SAVED_MASK UINT16_C(0x0000)

#define CVM_ABI_SYSCALL_NUMBER_REGISTER UINT8_C(0)
#define CVM_ABI_SYSCALL_ARGUMENT_FIRST UINT8_C(1)
#define CVM_ABI_SYSCALL_ARGUMENT_COUNT UINT8_C(6)

#endif
