#ifndef DISPLAY_PROTOCOL_H
#define DISPLAY_PROTOCOL_H

#include <stdint.h>

#define DISPLAY_MMIO_SIZE UINT64_C(104)
#define DISPLAY_MAX_WIDTH UINT64_C(1920)
#define DISPLAY_MAX_HEIGHT UINT64_C(1080)
#define DISPLAY_FORMAT_XRGB8888 UINT64_C(1)

#define DISPLAY_CONTROL_OFFSET         UINT64_C(0x00)
#define DISPLAY_WIDTH_OFFSET           UINT64_C(0x08)
#define DISPLAY_HEIGHT_OFFSET          UINT64_C(0x10)
#define DISPLAY_STRIDE_OFFSET          UINT64_C(0x18)
#define DISPLAY_FORMAT_OFFSET          UINT64_C(0x20)
#define DISPLAY_FRAMEBUFFER_OFFSET     UINT64_C(0x28)
#define DISPLAY_BUFFER_SIZE_OFFSET     UINT64_C(0x30)
#define DISPLAY_COMMAND_OFFSET         UINT64_C(0x38)
#define DISPLAY_STATUS_OFFSET          UINT64_C(0x40)
#define DISPLAY_FRAME_NUMBER_OFFSET    UINT64_C(0x48)
#define DISPLAY_IRQ_STATUS_OFFSET      UINT64_C(0x50)
#define DISPLAY_CAPABILITIES_OFFSET    UINT64_C(0x58)
#define DISPLAY_ERROR_CODE_OFFSET      UINT64_C(0x60)

#define DISPLAY_CONTROL_ENABLE     (UINT64_C(1) << 0)
#define DISPLAY_CONTROL_IRQ_ENABLE (UINT64_C(1) << 1)

#define DISPLAY_COMMAND_PRESENT UINT64_C(1)
#define DISPLAY_COMMAND_SET_MODE UINT64_C(2)

#define DISPLAY_STATUS_READY (UINT64_C(1) << 0)
#define DISPLAY_STATUS_BUSY  (UINT64_C(1) << 1)
#define DISPLAY_STATUS_ERROR (UINT64_C(1) << 2)

#define DISPLAY_IRQ_PRESENT_COMPLETE (UINT64_C(1) << 0)
#define DISPLAY_IRQ_ERROR            (UINT64_C(1) << 1)

#define DISPLAY_CAP_XRGB8888       (UINT64_C(1) << 0)
#define DISPLAY_CAP_EXPLICIT_PRESENT (UINT64_C(1) << 1)
#define DISPLAY_CAP_MODE_SET         (UINT64_C(1) << 2)

typedef enum {
    DISPLAY_ERROR_NONE = 0,
    DISPLAY_ERROR_DISABLED = 1,
    DISPLAY_ERROR_DIMENSIONS = 2,
    DISPLAY_ERROR_FORMAT = 3,
    DISPLAY_ERROR_STRIDE = 4,
    DISPLAY_ERROR_BUFFER_SIZE = 5,
    DISPLAY_ERROR_ALLOCATION = 6,
    DISPLAY_ERROR_DMA = 7,
    DISPLAY_ERROR_FRONTEND = 8,
    DISPLAY_ERROR_COMMAND = 9
} DisplayError;

#endif
