#ifndef IRQ_CONTROLLER_H
#define IRQ_CONTROLLER_H

#include <stdint.h>

#include "bus.h"
#include "interrupt.h"

#define IRQ_CONTROLLER_MMIO_BASE UINT64_C(0xFFFFFFFFFFFC3000)
#define IRQ_CONTROLLER_MMIO_SIZE UINT64_C(0x100)

#define IRQ_CONTROLLER_MAGIC UINT64_C(0x43515249)
#define IRQ_CONTROLLER_VERSION UINT64_C(1)

#define IRQ_CONTROLLER_MAGIC_OFFSET        UINT64_C(0x00)
#define IRQ_CONTROLLER_VERSION_OFFSET      UINT64_C(0x08)
#define IRQ_CONTROLLER_LINE_COUNT_OFFSET   UINT64_C(0x10)
#define IRQ_CONTROLLER_TARGET_COUNT_OFFSET UINT64_C(0x18)
#define IRQ_CONTROLLER_ENABLE_OFFSET       UINT64_C(0x20)
#define IRQ_CONTROLLER_ENABLE_SET_OFFSET   UINT64_C(0x28)
#define IRQ_CONTROLLER_ENABLE_CLEAR_OFFSET UINT64_C(0x30)
#define IRQ_CONTROLLER_PENDING_OFFSET      UINT64_C(0x38)
#define IRQ_CONTROLLER_ACTIVE_OFFSET       UINT64_C(0x40)
#define IRQ_CONTROLLER_LINE_SELECT_OFFSET  UINT64_C(0x48)
#define IRQ_CONTROLLER_ROUTE_OFFSET        UINT64_C(0x50)
#define IRQ_CONTROLLER_EOI_OFFSET          UINT64_C(0x58)
#define IRQ_CONTROLLER_RESULT_OFFSET       UINT64_C(0x60)
#define IRQ_CONTROLLER_FEATURES_OFFSET     UINT64_C(0x68)

#define IRQ_CONTROLLER_FEATURE_MASKING       (UINT64_C(1) << 0)
#define IRQ_CONTROLLER_FEATURE_ROUTING       (UINT64_C(1) << 1)
#define IRQ_CONTROLLER_FEATURE_EOI           (UINT64_C(1) << 2)
#define IRQ_CONTROLLER_FEATURE_FIXED_PRIORITY (UINT64_C(1) << 3)
#define IRQ_CONTROLLER_FEATURE_NO_REENTRY    (UINT64_C(1) << 4)

#define IRQ_CONTROLLER_RESULT_NONE           UINT64_C(0)
#define IRQ_CONTROLLER_RESULT_SUCCESS        UINT64_C(1)
#define IRQ_CONTROLLER_RESULT_INVALID_LINE   UINT64_C(2)
#define IRQ_CONTROLLER_RESULT_INVALID_TARGET UINT64_C(3)
#define IRQ_CONTROLLER_RESULT_BUSY           UINT64_C(4)
#define IRQ_CONTROLLER_RESULT_INVALID_MASK   UINT64_C(5)
#define IRQ_CONTROLLER_RESULT_NOT_ACTIVE     UINT64_C(6)

typedef struct {
    InterruptRouter *router;
    uint64_t selected_line;
    uint64_t last_result;
} IrqControllerDevice;

int irq_controller_device_init(IrqControllerDevice *device,
                               InterruptRouter *router);
BusDevice irq_controller_device_as_bus_device(IrqControllerDevice *device);

#endif
