#ifndef RISC_MV_RMFS_FORMAT_H
#define RISC_MV_RMFS_FORMAT_H

#include <stdint.h>

#define RMFS_MAGIC "RMVFS001"
#define RMFS_MAGIC_SIZE 8U
#define RMFS_VERSION_MAJOR 1U
#define RMFS_VERSION_MINOR 0U
#define RMFS_BLOCK_SIZE UINT32_C(4096)
#define RMFS_SECTORS_PER_BLOCK UINT32_C(8)
#define RMFS_INODE_SIZE UINT32_C(256)
#define RMFS_DIRENT_SIZE UINT32_C(256)
#define RMFS_NAME_MAX 239U
#define RMFS_INLINE_EXTENTS 6U
#define RMFS_MIN_INODE_COUNT UINT64_C(1024)
#define RMFS_MAX_INODE_COUNT UINT64_C(262144)
#define RMFS_BLOCKS_PER_INODE UINT64_C(1024)

#define RMFS_ROOT_INODE UINT64_C(1)
#define RMFS_BIN_INODE UINT64_C(2)
#define RMFS_INIT_INODE UINT64_C(3)

#define RMFS_MODE_TYPE_MASK UINT16_C(0170000)
#define RMFS_MODE_DIRECTORY UINT16_C(0040000)
#define RMFS_MODE_REGULAR UINT16_C(0100000)
#define RMFS_MODE_PERMISSIONS UINT16_C(0777)

#define RMFS_STATE_CLEAN UINT32_C(1)
#define RMFS_STATE_DIRTY UINT32_C(2)

/* Superblock byte offsets. Multibyte values are little-endian. */
#define RMFS_SB_MAGIC 0U
#define RMFS_SB_VERSION_MAJOR 8U
#define RMFS_SB_VERSION_MINOR 10U
#define RMFS_SB_BLOCK_SIZE 12U
#define RMFS_SB_INODE_SIZE 16U
#define RMFS_SB_STATE 20U
#define RMFS_SB_TOTAL_BLOCKS 24U
#define RMFS_SB_FREE_BLOCKS 32U
#define RMFS_SB_INODE_COUNT 40U
#define RMFS_SB_FREE_INODES 48U
#define RMFS_SB_ROOT_INODE 56U
#define RMFS_SB_INODE_BITMAP_START 64U
#define RMFS_SB_INODE_BITMAP_BLOCKS 72U
#define RMFS_SB_BLOCK_BITMAP_START 80U
#define RMFS_SB_BLOCK_BITMAP_BLOCKS 88U
#define RMFS_SB_INODE_TABLE_START 96U
#define RMFS_SB_INODE_TABLE_BLOCKS 104U
#define RMFS_SB_DATA_START 112U
#define RMFS_SB_BACKUP_BLOCK 120U
#define RMFS_SB_FEATURE_COMPAT 128U
#define RMFS_SB_FEATURE_RO_COMPAT 136U
#define RMFS_SB_FEATURE_INCOMPAT 144U
#define RMFS_SB_SEQUENCE 152U
#define RMFS_SB_UUID 160U
#define RMFS_SB_CHECKSUM 176U

/* Inode byte offsets. */
#define RMFS_IN_MODE 0U
#define RMFS_IN_FLAGS 2U
#define RMFS_IN_UID 4U
#define RMFS_IN_GID 8U
#define RMFS_IN_LINK_COUNT 12U
#define RMFS_IN_EXTENT_COUNT 16U
#define RMFS_IN_SIZE 24U
#define RMFS_IN_ATIME 32U
#define RMFS_IN_MTIME 40U
#define RMFS_IN_CTIME 48U
#define RMFS_IN_BTIME 56U
#define RMFS_IN_GENERATION 64U
#define RMFS_IN_PARENT 72U
#define RMFS_IN_EXTENTS 80U
#define RMFS_EXTENT_SIZE 24U
#define RMFS_EX_LOGICAL_BLOCK 0U
#define RMFS_EX_PHYSICAL_BLOCK 8U
#define RMFS_EX_BLOCK_COUNT 16U
#define RMFS_EX_FLAGS 20U
#define RMFS_IN_CHECKSUM 224U

/* Fixed-size directory entry byte offsets. */
#define RMFS_DE_INODE 0U
#define RMFS_DE_MODE 8U
#define RMFS_DE_NAME_LENGTH 10U
#define RMFS_DE_NAME 12U
#define RMFS_DE_CHECKSUM 252U

#endif
