#ifndef VIO_PROTOCOL_H
#define VIO_PROTOCOL_H

#include <stdint.h>

#define VIO_HUB_MMIO_BASE UINT64_C(0xFFFFFFFFFFFC0000)
#define VIO_HUB_MMIO_SIZE UINT64_C(4096)
#define VIO_HUB_MAGIC UINT64_C(0x314F4956)
#define VIO_HUB_ABI_VERSION UINT64_C(2)

#define VIO_HUB_MAGIC_OFFSET        UINT64_C(0x00)
#define VIO_HUB_ABI_OFFSET          UINT64_C(0x08)
#define VIO_HUB_SLOT_COUNT_OFFSET   UINT64_C(0x10)
#define VIO_HUB_GENERATION_OFFSET   UINT64_C(0x18)
#define VIO_HUB_EVENT_STATUS_OFFSET UINT64_C(0x20)
#define VIO_HUB_EVENT_ACK_OFFSET    UINT64_C(0x28)
#define VIO_HUB_SLOT_BASE           UINT64_C(0x100)
#define VIO_HUB_SLOT_STRIDE         UINT64_C(0xC0)

#define VIO_SLOT_STATUS_OFFSET         UINT64_C(0x00)
#define VIO_SLOT_CLASS_OFFSET          UINT64_C(0x08)
#define VIO_SLOT_VENDOR_OFFSET         UINT64_C(0x10)
#define VIO_SLOT_DEVICE_OFFSET         UINT64_C(0x18)
#define VIO_SLOT_VERSION_OFFSET        UINT64_C(0x20)
#define VIO_SLOT_BAR0_BASE_OFFSET      UINT64_C(0x28)
#define VIO_SLOT_BAR0_SIZE_OFFSET      UINT64_C(0x30)
#define VIO_SLOT_IRQ0_OFFSET           UINT64_C(0x38)
#define VIO_SLOT_FEATURES_OFFSET       UINT64_C(0x40)
#define VIO_SLOT_DEVICE_ABI_OFFSET     UINT64_C(0x48)
#define VIO_SLOT_BAR_COUNT_OFFSET      UINT64_C(0x50)
#define VIO_SLOT_IRQ_COUNT_OFFSET      UINT64_C(0x58)
#define VIO_SLOT_BAR1_BASE_OFFSET      UINT64_C(0x60)
#define VIO_SLOT_BAR1_SIZE_OFFSET      UINT64_C(0x68)
#define VIO_SLOT_BAR2_BASE_OFFSET      UINT64_C(0x70)
#define VIO_SLOT_BAR2_SIZE_OFFSET      UINT64_C(0x78)
#define VIO_SLOT_BAR3_BASE_OFFSET      UINT64_C(0x80)
#define VIO_SLOT_BAR3_SIZE_OFFSET      UINT64_C(0x88)
#define VIO_SLOT_IRQ1_OFFSET           UINT64_C(0x90)
#define VIO_SLOT_IRQ2_OFFSET           UINT64_C(0x98)
#define VIO_SLOT_IRQ3_OFFSET           UINT64_C(0xA0)

#define VIO_SLOT_STATUS_PRESENT  (UINT64_C(1) << 0)
#define VIO_SLOT_STATUS_EXTERNAL (UINT64_C(1) << 1)
#define VIO_HUB_EVENT_DEVICE_ADDED (UINT64_C(1) << 0)
#define VIO_HUB_EVENT_DEVICE_REMOVED (UINT64_C(1) << 1)

#endif
